#!/usr/bin/env bash
INPUT_FILE_DAVID=${1?Error: No input file given}
OUTPUT_FOLDER_DAVID=${2?Error: No output folder given}
export INPUT_FILE_DAVID
export OUTPUT_FOLDER_DAVID
A2="$(cut -d'_' -f2 <<<$OUTPUT_FOLDER_DAVID)"
A3="$(cut -d '_' -f3 <<<$OUTPUT_FOLDER_DAVID)"
A="${A2}_${A3}"
for i_theta in {50..210..5} ; 
do

export OUTPUT_FOLDER_COMPOUND=${i_theta}deg
export OUT_FILE=../7_RESULTS/$OUTPUT_FOLDER_DAVID/$OUTPUT_FOLDER_COMPOUND/INCS_$OUTPUT_FOLDER_COMPOUND.out
export ERR_FILE=../7_RESULTS/$OUTPUT_FOLDER_DAVID/$OUTPUT_FOLDER_COMPOUND/INCS_$OUTPUT_FOLDER_COMPOUND.err

cd ../2_SOURCE_CODE/
# rm ../3_COMPILED_FILES/INCS_*
make 
cp ../3_COMPILED_FILES/INCS_Agis ../3_COMPILED_FILES/INCS_$OUTPUT_FOLDER_COMPOUND

#if [ -d ../7_RESULTS/$OUTPUT_FOLDER_DAVID]; then
	mkdir ../7_RESULTS/$OUTPUT_FOLDER_DAVID/$OUTPUT_FOLDER_COMPOUND
	mkdir ../7_RESULTS/$OUTPUT_FOLDER_DAVID/$OUTPUT_FOLDER_COMPOUND/2_SOURCE_CODE/
#	echo "Directory is created ..."
#fi

cd ../7_RESULTS/$OUTPUT_FOLDER_DAVID/$OUTPUT_FOLDER_COMPOUND
find . -name '*GlobalLoc*' | xargs rm -f
mkdir 2_SOURCE_CODE

cd ../../../2_SOURCE_CODE/

rm ../7_RESULTS/$OUTPUT_FOLDER_DAVID/$OUTPUT_FOLDER_COMPOUND/*
cp *.f90 ../7_RESULTS/$OUTPUT_FOLDER_DAVID/$OUTPUT_FOLDER_COMPOUND/2_SOURCE_CODE/
sed "80s/.*/td_${OUTPUT_FOLDER_COMPOUND}_x.dat/" ../5_INPUT_FILES/$INPUT_FILE_DAVID > ../5_INPUT_FILES/INCS_TEMP.in
sed "82s/.*/apod_${OUTPUT_FOLDER_COMPOUND}_x.dat/" ../5_INPUT_FILES/INCS_TEMP.in > ../5_INPUT_FILES/$INPUT_FILE_DAVID
cp ../5_INPUT_FILES/$INPUT_FILE_DAVID ../7_RESULTS/$OUTPUT_FOLDER_DAVID/$OUTPUT_FOLDER_COMPOUND/
cp ../5_INPUT_FILES/$OUTPUT_FOLDER_DAVID/TD/td_${OUTPUT_FOLDER_COMPOUND}_x.dat ../7_RESULTS/$OUTPUT_FOLDER_DAVID/$OUTPUT_FOLDER_COMPOUND/
cp ../5_INPUT_FILES/$OUTPUT_FOLDER_DAVID/APOD/apod_${OUTPUT_FOLDER_COMPOUND}_x.dat ../7_RESULTS/$OUTPUT_FOLDER_DAVID/$OUTPUT_FOLDER_COMPOUND/

cd ../6_RUN/

### HERE WE CREATE THE BASH FILE
echo "#!/bin/bash  									 															
   											 															
#SBATCH --job-name=${A}_wave  	 																		
#SBATCH --partition=general  					 															
#SBATCH --qos=short           				 															
#SBATCH --nodes=2            					 															
#SBATCH --ntasks-per-node=50  				 															
#SBATCH --cpus-per-task=1       				 															
#SBATCH --mem=400G            				 															
#SBATCH --time=04:00:00       				 															
#SBATCH --output=$OUT_FILE  					 															
#SBATCH --error=$ERR_FILE      				 															
##SBATCH --exclusive           				 															
   											 															
module use /opt/insy/modulefiles  			 															
module load intel  							 															
   											 															
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/bin/compilervars.sh intel64  		
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/mpi/bin64/mpivars.sh  				
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/mkl/bin/mklvars.sh intel64  		
   																										
ulimit -s unlimited  																						
   																										
# export I_MPI_PMI_LIBRARY=/home/opt/slurm/slurm-17.11.5/src/api/.libs/libpmi.so  						
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so  															
export OMP_NUM_THREADS=1  																				
export MKL_NUM_THREADS=1  																				
#export MKL_THREADING_LAYER=intel  																		
#export MKL_DYNAMIC= FALSE   																				
#export MKL_VERBOSE=1  																					
srun ../3_COMPILED_FILES/INCS_${OUTPUT_FOLDER_COMPOUND} $INPUT_FILE_DAVID TESTNeumann ../7_RESULTS/$OUTPUT_FOLDER_DAVID/$OUTPUT_FOLDER_COMPOUND ../7_RESULTS/$OUTPUT_FOLDER_DAVID/$OUTPUT_FOLDER_COMPOUND" > job_INCS_David

sbatch ../6_RUN/job_INCS_David &

sleep 5
squeue --format="%.18i %.9P %.30j %.8u %.8T %.10M %.9l %.6D %R" --me
done
