#!/usr/bin/env bash
INPUT_FILE_DAVID=${1?Error: No input file given}
OUTPUT_FOLDER_DAVID=${2?Error: No output folder given}
export INPUT_FILE_DAVID
export OUTPUT_FOLDER_DAVID
echo $INPUT_FILE_DAVID
echo $OUTPUT_FOLDER_DAVID

IFS=/ read OUTPUT_FOLDER_NAME OUTPUT_FILE_NAME <<< $OUTPUT_FOLDER_DAVID
echo $OUTPUT_FOLDER_NAME
echo $OUTPUT_FILE_NAME
echo $OUTPUT_FOLDER_DAVID
INPUT_FOLDER="//tudelft.net/staff-groups/tnw/ist/ak/Promovendi/agismatalliota/INCS_XWAVE"

A2="$(cut -d'_' -f2 <<<$OUTPUT_FILE_NAME)"
A3="$(cut -d '_' -f3 <<<$OUTPUT_FILE_NAME)"
A="${A2}_${A3}"

for press in {75..75..25} ; 
do

val_shift=$(echo " ${press}/25 -1" |bc)
# export OUTPUT_FOLDER_COMPOUND="5E4MBs_Positive_1_5MHz_${press}kPa_p${val_shift}_long"
export OUTPUT_FOLDER_COMPOUND="1E4MBs_Positive_1MHz_poly_${press}kPa_stronger"
export OUTPUT_FOLDER_DAVID=$OUTPUT_FOLDER_NAME/${OUTPUT_FOLDER_COMPOUND}

export OUT_FILE=$INPUT_FOLDER/7_RESULTS/$OUTPUT_FOLDER_DAVID/INCS_${OUTPUT_FILE_NAME}_${OUTPUT_FOLDER_COMPOUND}.out
export ERR_FILE=$INPUT_FOLDER/7_RESULTS/$OUTPUT_FOLDER_DAVID/INCS_${OUTPUT_FILE_NAME}_${OUTPUT_FOLDER_COMPOUND}.err

cd $INPUT_FOLDER/2_SOURCE_CODE/
make 
cp ../3_COMPILED_FILES/INCS_Agis ../3_COMPILED_FILES/INCS_Agis_${OUTPUT_FILE_NAME}

mkdir $INPUT_FOLDER/7_RESULTS/$OUTPUT_FOLDER_NAME
mkdir $INPUT_FOLDER/7_RESULTS/$OUTPUT_FOLDER_DAVID
mkdir $INPUT_FOLDER/7_RESULTS/$OUTPUT_FOLDER_DAVID/2_SOURCE_CODE/

rm $INPUT_FOLDER/7_RESULTS/$OUTPUT_FOLDER_DAVID/*
rm $INPUT_FOLDER/7_RESULTS/$OUTPUT_FOLDER_DAVID/Bubbles/*

cp ../2_SOURCE_CODE/*.f90 $INPUT_FOLDER/7_RESULTS/$OUTPUT_FOLDER_DAVID/2_SOURCE_CODE/

val=$(echo "scale=4; (${press}/25 -1)*0.05" |bc)
val_press=$(echo "scale=4; ${press}*1000" |bc)
# sed "152s/.*/${val}/" ../5_INPUT_FILES/$INPUT_FILE_DAVID > ../5_INPUT_FILES/INCS_TEMP.in
# sed "175s/.*/${val}/" ../5_INPUT_FILES/INCS_TEMP.in > ../5_INPUT_FILES/$INPUT_FILE_DAVID
# sed "193s/.*/${val}/" ../5_INPUT_FILES/$INPUT_FILE_DAVID > ../5_INPUT_FILES/INCS_TEMP.in
sed "61s/.*/${val_press}/" ../5_INPUT_FILES/$INPUT_FILE_DAVID > ../5_INPUT_FILES/INCS_TEMP.in  
sed "61s/.*/${val_press}/" ../5_INPUT_FILES/INCS_TEMP.in > ../5_INPUT_FILES/$INPUT_FILE_DAVID

cp ../5_INPUT_FILES/$INPUT_FILE_DAVID $INPUT_FOLDER/7_RESULTS/$OUTPUT_FOLDER_DAVID/
cp ../3_COMPILED_FILES/INCS_Agis_${OUTPUT_FILE_NAME} $INPUT_FOLDER/7_RESULTS/$OUTPUT_FOLDER_DAVID/

cd $INPUT_FOLDER/6_RUN/

### HERE WE CREATE THE BASH FILE
echo "#!/bin/bash  						 															
   											 															
#SBATCH --job-name=${OUTPUT_FOLDER_COMPOUND} 	 																
#SBATCH --partition=imphys,general  					 													
#SBATCH --qos=medium           				 															
#SBATCH --nodes=1-2           					 															
##SBATCH --constraint=ib  				 																
##SBATCH --network=IB  				 																	
#SBATCH --ntasks=100  		 																			
#SBATCH --cpus-per-task=1     				 															
#SBATCH --mem-per-cpu=5000M  				 															
###SBATCH  --exclusive    						 														
#SBATCH --time=04:00:00       				 															
#SBATCH --output=${OUT_FILE}  					 															
#SBATCH --error=${ERR_FILE}      				 															
   											 															
module use /opt/insy/modulefiles  			 															
module load intel  							 															
   											 															
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/bin/compilervars.sh intel64  		
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/mpi/bin64/mpivars.sh  				
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/mkl/bin/mklvars.sh intel64  		
   																										
##ulimit -s unlimited  																						
##ulimit -l unlimited  																					
   							
export MPIR_CVAR_CH4_OFI_TAG_BITS=31
export MPIR_CVAR_CH4_OFI_RANK_BITS=8 		

# export I_MPI_PMI_LIBRARY=/home/opt/slurm/slurm-17.11.5/src/api/.libs/libpmi.so  						
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so  															
export OMP_NUM_THREADS=1  																				
export MKL_NUM_THREADS=1  																				
#export MKL_THREADING_LAYER=intel  																		
#export MKL_DYNAMIC= 'FALSE'  																				
#export MKL_VERBOSE=1  			
			 																							
srun ${INPUT_FOLDER}/7_RESULTS/${OUTPUT_FOLDER_DAVID}/INCS_Agis_${OUTPUT_FILE_NAME} ${INPUT_FILE_DAVID} TESTNeumann ../7_RESULTS/${OUTPUT_FOLDER_DAVID} ../7_RESULTS/${OUTPUT_FOLDER_DAVID}" > job_INCS_GG

sbatch ${INPUT_FOLDER}/6_RUN/job_INCS_GG &
sleep 5
# squeue --format="%.18i %.9P %.80j %.8u %.8T %.10M %.9l %.6D %R" --me
done