#!/usr/bin/env bash
INPUT_FILE=${1?Error: No input file given}
OUTPUT_FOLDER=${2?Error: No output folder given}
export INPUT_FILE
export OUTPUT_FOLDER

export OUT_FILE=../7_RESULTS/$OUTPUT_FOLDER/INCS_$OUTPUT_FOLDER.out
export ERR_FILE=../7_RESULTS/$OUTPUT_FOLDER/INCS_$OUTPUT_FOLDER.err
echo $OUT_FILE
echo $ERR_FILE

cd ../2_SOURCE_CODE/
rm ../3_COMPILED_FILES/INCS_Agis_*
make
cp ../3_COMPILED_FILES/INCS_Agis ../3_COMPILED_FILES/INCS_Agis_${OUTPUT_FOLDER}

#if [ -d ../7_RESULTS/$OUTPUT_FOLDER]; then
mkdir ../7_RESULTS/$OUTPUT_FOLDER
#	echo "Directory is created ..."
#fi

cd ../7_RESULTS/$OUTPUT_FOLDER/
find . -name '*GlobalLoc*' | xargs rm -f
mkdir 2_SOURCE_CODE

cd ../../2_SOURCE_CODE/
rm ../7_RESULTS/$OUTPUT_FOLDER/*
rm ../7_RESULTS/$OUTPUT_FOLDER/Bubbles/*
cp *.f90 ../7_RESULTS/$OUTPUT_FOLDER/2_SOURCE_CODE/
cp ../5_INPUT_FILES/$INPUT_FILE ../7_RESULTS/$OUTPUT_FOLDER/

cd ../6_RUN/
### HERE WE CREATE THE BASH FILE
echo "#!/bin/bash" > job_INCS_long
echo " " >> job_INCS_long
echo "#SBATCH --job-name=2_MONO_$OUTPUT_FOLDER" 		>> job_INCS_long
echo "#SBATCH --partition=imphys" 						>> job_INCS_long
echo "#SBATCH --qos=long"          						>> job_INCS_long
echo "#SBATCH --nodes=1"           						>> job_INCS_long
echo "#SBATCH --ntasks-per-node=56" 					>> job_INCS_long
echo "#SBATCH --cpus-per-task=1"    					>> job_INCS_long
echo "#SBATCH --mem=500G"           					>> job_INCS_long
echo "#SBATCH --time=20:00:00"      					>> job_INCS_long
echo "#SBATCH --output=$OUT_FILE" 						>> job_INCS_long
echo "#SBATCH --error=$ERR_FILE"     					>> job_INCS_long
echo "##SBATCH --exclusive"          					>> job_INCS_long
echo " " 												>> job_INCS_long
echo "module use /opt/insy/modulefiles" 				>> job_INCS_long
echo "module load intel" 								>> job_INCS_long
echo " " 												>> job_INCS_long
echo "source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/bin/compilervars.sh intel64" 		>> job_INCS_long
echo "source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/mpi/bin64/mpivars.sh" 				>> job_INCS_long
echo "source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/mkl/bin/mklvars.sh intel64" 		>> job_INCS_long
echo " " 												>> job_INCS_long
echo "ulimit -s unlimited" 								>> job_INCS_long
echo " " 												>> job_INCS_long
echo "# export I_MPI_PMI_LIBRARY=/home/opt/slurm/slurm-17.11.5/src/api/.libs/libpmi.so" 						>> job_INCS_long
echo "export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so" 	>> job_INCS_long
echo "export OMP_NUM_THREADS=1" 						>> job_INCS_long
echo "export MKL_NUM_THREADS=1" 						>> job_INCS_long
echo "#export MKL_THREADING_LAYER=intel" 				>> job_INCS_long
echo "#export MKL_DYNAMIC="FALSE"" 						>> job_INCS_long
echo "#export MKL_VERBOSE=1" 							>> job_INCS_long
echo "srun ../3_COMPILED_FILES/INCS_Agis_${OUTPUT_FOLDER} $INPUT_FILE TESTNeumann ../5_INPUT_FILES ../7_RESULTS/$OUTPUT_FOLDER" >> job_INCS_long

sbatch ../6_RUN/job_INCS_long &

sleep 5
qstat -u agismatalliota
