#!/usr/bin/env bash
INPUT_FILE_DAVID=${1?Error: No input file given}
OUTPUT_FOLDER_DAVID=${2?Error: No output folder given}
export INPUT_FILE_DAVID
export OUTPUT_FOLDER_DAVID
echo $INPUT_FILE_DAVID 
echo $OUTPUT_FOLDER_DAVID

IFS=/ read OUTPUT_FOLDER_NAME OUTPUT_FILE_NAME <<< $OUTPUT_FOLDER_DAVID
echo $OUTPUT_FOLDER_NAME
echo $OUTPUT_FILE_NAME
echo $OUTPUT_FOLDER_DAVID
INPUT_FOLDER="//tudelft.net/staff-groups/tnw/ist/ak/Promovendi/agismatalliota/INCS_3D_PS_CLOUD"
echo $INPUT_FOLDER
A2="$(cut -d'_' -f2 <<<$OUTPUT_FILE_NAME)"
A3="$(cut -d '_' -f3 <<<$OUTPUT_FILE_NAME)"
A="${A2}_${A3}"

Freq=1.5
# MBside=2
# side=5
# for Freq in {1.7,4} ; 
# do
MBside=4;
# for MBside in {0.5,1,2,4}
# do
side=2;
# for side in {2}
# do

val=$(echo "scale=4; ${side}*2" |bc)
val=${val%.*}
 
val_MB=$(echo "scale=4; ${MBside}*2" |bc)
val_MB=${val_MB%.*}

Freq_Val=$(echo "scale=4; ${Freq}*10" |bc)
Freq_Val=${Freq_Val%.*}

export OUTPUT_FOLDER_COMPOUND=SRC${val}_25MB${val_MB}_6um
export OUTPUT_SUBFOLDER=600PS_${Freq_Val}MHz_$OUTPUT_FOLDER_COMPOUND
export OUTPUT_FOLDER_DAVID=$OUTPUT_FOLDER_NAME/${OUTPUT_SUBFOLDER}
RNM_FOLDER=$INPUT_FOLDER/7_RESULTS/$OUTPUT_FOLDER_DAVID
export OUT_FILE=$RNM_FOLDER/INCS_${OUTPUT_SUBFOLDER}.out
export ERR_FILE=$RNM_FOLDER/INCS_${OUTPUT_SUBFOLDER}.err

echo $OUT_FILE
cd ../2_SOURCE_CODE/
make
cp ../3_COMPILED_FILES/INCS_Agis ../3_COMPILED_FILES/INCS_${OUTPUT_SUBFOLDER}

mkdir $INPUT_FOLDER/7_RESULTS/$OUTPUT_FOLDER_NAME
mkdir $RNM_FOLDER
mkdir $RNM_FOLDER/2_SOURCE_CODE/
mkdir $RNM_FOLDER/Bubbles/

rm $RNM_FOLDER/*
rm $RNM_FOLDER/Bubbles/*

val_zmid=5;
val_m=$(echo "scale=4; -${side}*1480/(${Freq}*1000)/2" |bc)
val_p=$(echo "scale=4;  ${side}*1480/(${Freq}*1000)/2" |bc)
val_zs=$(echo "scale=4; ${val_zmid}-${side}*1480/(${Freq}*1000)/2" |bc)
val_ze=$(echo "scale=4; ${val_zmid}+${side}*1480/(${Freq}*1000)/2" |bc)
num_source_lambda=600
val_num_source=$(echo "scale=4; ${num_source_lambda}*(${side})^3" |bc)

export xlim="${val_m} ${val_p}"
export ylim="${val_m} ${val_p}"
export zlim="${val_zs} ${val_ze}"

freq_val=$(echo "scale=4; ${Freq}*1000000" |bc)

Freq_MB=1.5
val_MB_m=$(echo "scale=4; -${MBside}*1480/(${Freq_MB}*1000)/2" |bc)
val_MB_p=$(echo "scale=4;  ${MBside}*1480/(${Freq_MB}*1000)/2" |bc)
val_MB_zs=$(echo "scale=4; ${val_zmid}-${MBside}*1480/(${Freq_MB}*1000)/2" |bc)
val_MB_ze=$(echo "scale=4; ${val_zmid}+${MBside}*1480/(${Freq_MB}*1000)/2" |bc)
num_source_lambda_MBs=25
val_num_source_MBs=$(echo "scale=4; ${num_source_lambda_MBs}*(${MBside})^3" |bc)

export xlim_MB="${val_MB_m} ${val_MB_p}"
export ylim_MB="${val_MB_m} ${val_MB_p}"
export zlim_MB="${val_MB_zs} ${val_MB_ze}"

cp ../5_INPUT_FILES/$INPUT_FILE_DAVID $RNM_FOLDER/

sed "38s/.*/$xlim/" ${RNM_FOLDER}/$INPUT_FILE_DAVID > ${RNM_FOLDER}/INCS_TEMP.in
sed "39s/.*/$ylim/" ${RNM_FOLDER}/INCS_TEMP.in > ${RNM_FOLDER}/$INPUT_FILE_DAVID
sed "40s/.*/$zlim/" ${RNM_FOLDER}/$INPUT_FILE_DAVID > ${RNM_FOLDER}/INCS_TEMP.in
sed "26s/.*/$freq_val/" ${RNM_FOLDER}/INCS_TEMP.in > ${RNM_FOLDER}/$INPUT_FILE_DAVID
sed "142s/.*/$xlim_MB/" ${RNM_FOLDER}/$INPUT_FILE_DAVID > ${RNM_FOLDER}/INCS_TEMP.in
sed "143s/.*/$ylim_MB/" ${RNM_FOLDER}/INCS_TEMP.in > ${RNM_FOLDER}/$INPUT_FILE_DAVID
sed "144s/.*/$zlim_MB/" ${RNM_FOLDER}/$INPUT_FILE_DAVID > ${RNM_FOLDER}/INCS_TEMP.in
sed "34s/.*/$val_num_source/" ${RNM_FOLDER}/INCS_TEMP.in > ${RNM_FOLDER}/$INPUT_FILE_DAVID
sed "137s/.*/$val_num_source_MBs/" ${RNM_FOLDER}/$INPUT_FILE_DAVID > ${RNM_FOLDER}/INCS_TEMP.in
cp ${RNM_FOLDER}/INCS_TEMP.in ${RNM_FOLDER}/$INPUT_FILE_DAVID

cp ../2_SOURCE_CODE/*.f90 ${RNM_FOLDER}/2_SOURCE_CODE/
cp ../3_COMPILED_FILES/INCS_${OUTPUT_SUBFOLDER} ${RNM_FOLDER}/
cd $INPUT_FOLDER/6_RUN/

### HERE WE CREATE THE BASH FILE
echo "#!/bin/bash  									 															
   											 															
#SBATCH --job-name=${OUTPUT_SUBFOLDER}  	 																		
#SBATCH --partition=general  					 															
#SBATCH --qos=short           				 															
#SBATCH --nodes=1-2           					 															
#SBATCH --ntasks=50  				 															
#SBATCH --cpus-per-task=1      				 															
#SBATCH --mem-per-cpu=9G             				 															
#SBATCH --time=04:00:00       				 															
#SBATCH --output=$OUT_FILE  					 															
#SBATCH --error=$ERR_FILE      				 															
##SBATCH --exclusive           				 															
   										 															
module use /opt/insy/modulefiles  			 															
module load intel/2017u4				 															
   											 															
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/bin/compilervars.sh intel64  		
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/mpi/bin64/mpivars.sh  				
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/mkl/bin/mklvars.sh intel64  		
   					
##ulimit -a 		 																						
##ulimit -s unlimited  																						
##ulimit -a 		 																						
##ulimit -l unlimited  																						
   					
export MPIR_CVAR_CH4_OFI_TAG_BITS=31  # BITS FOR TAG TO EXTEND THE LENGTH
export MPIR_CVAR_CH4_OFI_RANK_BITS=8  # BITS FOR NUMBER OF PROCESS. SUMMATION OF BOTH SHOULD BE <= 39																				
   																										
# export I_MPI_PMI_LIBRARY=/home/opt/slurm/slurm-17.11.5/src/api/.libs/libpmi.so  						
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so  															
export OMP_NUM_THREADS=1  																				
export MKL_NUM_THREADS=1  																				
#export MKL_THREADING_LAYER=intel  																		
#export MKL_DYNAMIC= FALSE   																				
#export MKL_VERBOSE=1  																					
srun ${RNM_FOLDER}/INCS_${OUTPUT_SUBFOLDER} ${INPUT_FILE_DAVID} TESTNeumann ${RNM_FOLDER}/ ${RNM_FOLDER}/" > job_INCS_David

cp $INPUT_FOLDER/6_RUN/job_INCS_David ${RNM_FOLDER}/

sbatch $INPUT_FOLDER/6_RUN/job_INCS_David &
# sleep 5
# squeue --format="%.18i %.9P %.80j %.8u %.8T %.10M %.9l %.6D %R" --me
# done
# done
# done
