#!/bin/bash  									 															
   											 															
#SBATCH --job-name=PW_1MHz_2E5Pa_9Fnyq_5E4MBs_MD_2_8um_40iter_1E14  	 														     	
#SBATCH --partition=imphys,general  					 													
#SBATCH --qos=long           				 															
#SBATCH --nodes=1-2         					 															
#SBATCH --ntasks=100  				 																		
#SBATCH --cpus-per-task=1     				 															
#SBATCH --mem-per-cpu=9G            				 														
#SBATCH --time=100:00:00      				 															
#SBATCH --output=../7_RESULTS/test/PW_1MHz_2E5Pa_9Fnyq_5E4MBs_MD_2_8um_40iter_1E14/INCS_PW_1MHz_2E5Pa_9Fnyq_5E4MBs_MD_2_8um_40iter_1E14.out  					 															
#SBATCH --error=../7_RESULTS/test/PW_1MHz_2E5Pa_9Fnyq_5E4MBs_MD_2_8um_40iter_1E14/INCS_PW_1MHz_2E5Pa_9Fnyq_5E4MBs_MD_2_8um_40iter_1E14.err      				 															
##SBATCH --exclusive    
##SBATCH --constraint=IB     				 														
   											 															
module use /opt/insy/modulefiles  			 															
module load intel/2017u4									 															
   											 															
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/bin/compilervars.sh intel64  		
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/mpi/bin64/mpivars.sh  				
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/mkl/bin/mklvars.sh intel64  		
   																										
##ulimit -a 		 																						
##ulimit -s unlimited  																						
##ulimit -a 		 																						
##ulimit -l unlimited  																						
   					
export MPIR_CVAR_CH4_OFI_TAG_BITS=31  # BITS FOR TAG TO EXTEND THE LENGTH
export MPIR_CVAR_CH4_OFI_RANK_BITS=8  # BITS FOR NUMBER OF PROCESS. SUMMATION OF BOTH SHOULD BE <= 39
																											
# export I_MPI_PMI_LIBRARY=/home/opt/slurm/slurm-17.11.5/src/api/.libs/libpmi.so  						
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so  															
export OMP_NUM_THREADS=1  																				
export MKL_NUM_THREADS=1  																				
#export MKL_THREADING_LAYER=intel  																		
#export MKL_DYNAMIC= 'FALSE'  																				
#export MKL_VERBOSE=1  																					
srun ../7_RESULTS/test/PW_1MHz_2E5Pa_9Fnyq_5E4MBs_MD_2_8um_40iter_1E14/INCS_Agis_PW_1MHz_2E5Pa_9Fnyq_5E4MBs_MD_2_8um_40iter_1E14 ../7_RESULTS/test/PW_1MHz_2E5Pa_9Fnyq_5E4MBs_MD_2_8um_40iter_1E14/TESTNeumann_Planewave_MultiBubble.in TESTNeumann ../5_INPUT_FILES ../7_RESULTS/test/PW_1MHz_2E5Pa_9Fnyq_5E4MBs_MD_2_8um_40iter_1E14
