#!/bin/bash
 
#SBATCH --job-name=David_210deg_x_NL_Only
#SBATCH --partition=general
#SBATCH --qos=short
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=54
#SBATCH --cpus-per-task=1
#SBATCH --mem=300G
#SBATCH --time=04:00:00
#SBATCH --output=../7_RESULTS/David_210deg_x_NL_Only/INCS_David_210deg_x_NL_Only.out
#SBATCH --error=../7_RESULTS/David_210deg_x_NL_Only/INCS_David_210deg_x_NL_Only.err
##SBATCH --exclusive
 
module use /opt/insy/modulefiles
module load intel
 
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/bin/compilervars.sh intel64
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/mpi/bin64/mpivars.sh
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/mkl/bin/mklvars.sh intel64
 
ulimit -s unlimited
 
# export I_MPI_PMI_LIBRARY=/home/opt/slurm/slurm-17.11.5/src/api/.libs/libpmi.so
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
#export MKL_THREADING_LAYER=intel
#export MKL_DYNAMIC=FALSE
#export MKL_VERBOSE=1
srun ../3_COMPILED_FILES/INCS_Agis_David_210deg_x_NL_Only TESTNeumann_David_small_phased_array_planewave.in TESTNeumann ../7_RESULTS/David_210deg_x_NL_Only ../7_RESULTS/David_210deg_x_NL_Only
