#!/bin/bash
 
#SBATCH --job-name=2_MONO_1E3PS_2E4MBs_A78_LongPulse
#SBATCH --partition=general
#SBATCH --qos=long
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=56
#SBATCH --cpus-per-task=1
#SBATCH --mem=500G
#SBATCH --time=40:00:00
#SBATCH --output=../7_RESULTS/1E3PS_2E4MBs_A78_LongPulse/INCS_1E3PS_2E4MBs_A78_LongPulse.out
#SBATCH --error=../7_RESULTS/1E3PS_2E4MBs_A78_LongPulse/INCS_1E3PS_2E4MBs_A78_LongPulse.err
##SBATCH --exclusive
 
module use /opt/insy/modulefiles
module load intel
 
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/bin/compilervars.sh intel64
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/mpi/bin64/mpivars.sh
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/mkl/bin/mklvars.sh intel64
 
ulimit -s unlimited
 
# export I_MPI_PMI_LIBRARY=/home/opt/slurm/slurm-17.11.5/src/api/.libs/libpmi.so
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
#export MKL_THREADING_LAYER=intel
#export MKL_DYNAMIC=FALSE
#export MKL_VERBOSE=1
srun ../3_COMPILED_FILES/INCS_Agis_1E3PS_2E4MBs_A78_LongPulse TESTNeumann_PointSourceCloud_MultiBubble.in TESTNeumann ../5_INPUT_FILES ../7_RESULTS/1E3PS_2E4MBs_A78_LongPulse
