#!/bin/bash  									 															
   											 															
#SBATCH --job-name=David_200deg_x_Lagrangian_FFT_001_SourceInit  	 																
#SBATCH --partition=imphys,general  					 													
#SBATCH --qos=medium           				 															
###SBATCH --nodes=2            					 															
#SBATCH --constraint=ib  				 																
##SBATCH --network=IB  				 																	
#SBATCH --ntasks=100  		 																			
#SBATCH --cpus-per-task=1     				 															
#SBATCH --mem-per-cpu=9000M  				 															
###SBATCH  --exclusive    						 														
#SBATCH --time=36:00:00       				 															
#SBATCH --output=../7_RESULTS/Validation/David_200deg_x_Lagrangian_FFT_001_SourceInit/INCS_David_200deg_x_Lagrangian_FFT_001_SourceInit.out  					 															
#SBATCH --error=../7_RESULTS/Validation/David_200deg_x_Lagrangian_FFT_001_SourceInit/INCS_David_200deg_x_Lagrangian_FFT_001_SourceInit.err      				 															
   											 															
module use /opt/insy/modulefiles  			 															
module load intel  							 															
   											 															
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/bin/compilervars.sh intel64  		
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/mpi/bin64/mpivars.sh  				
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/mkl/bin/mklvars.sh intel64  		
   																										
ulimit -s unlimited  																						
##ulimit -l unlimited  																					
   																										
# export I_MPI_PMI_LIBRARY=/home/opt/slurm/slurm-17.11.5/src/api/.libs/libpmi.so  						
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so  															
export OMP_NUM_THREADS=1  																				
export MKL_NUM_THREADS=1  																				
#export MKL_THREADING_LAYER=intel  																		
#export MKL_DYNAMIC= 'FALSE'  																				
#export MKL_VERBOSE=1  																					
srun ../7_RESULTS/Validation/David_200deg_x_Lagrangian_FFT_001_SourceInit/INCS_Agis_David_200deg_x_Lagrangian_FFT_001_SourceInit TESTNeumann_David_phased_array_validation.in TESTNeumann ../7_RESULTS/Validation/David_200deg_x_Lagrangian_FFT_001_SourceInit ../7_RESULTS/Validation/David_200deg_x_Lagrangian_FFT_001_SourceInit
