#!/bin/bash
 
#SBATCH --job-name=15deg_right_wave
#SBATCH --partition=general
#SBATCH --qos=long
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=56
#SBATCH --cpus-per-task=1
#SBATCH --mem=350G
#SBATCH --time=07:00:00
#SBATCH -o ../7_Results/David_15deg_right/INCS_David.out
#SBATCH -e ../7_Results/David_15deg_right/INCS_David.err
 
module use /opt/insy/modulefiles
module load intel
 
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/bin/compilervars.sh intel64
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/mpi/bin64/mpivars.sh
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/mkl/bin/mklvars.sh intel64
 
# export I_MPI_PMI_LIBRARY=/home/opt/slurm/slurm-17.11.5/src/api/.libs/libpmi.so
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
#export MKL_THREADING_LAYER=intel
#export MKL_DYNAMIC=FALSE
#export MKL_VERBOSE=1
srun ../3_Compiled_Files_3/INCS_Agis TESTNeumann_David.in TESTNeumann ../7_Results/David_15deg_right ../7_Results/David_15deg_right
