#!/bin/bash
 
#SBATCH --job-name=PW_2E5Pa_1micron_1MHz_2E5LS
#SBATCH --partition=imphys,general
#SBATCH --qos=medium
#SBATCH --ntasks=48
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=10G
#SBATCH --time=36:00:00
#SBATCH --output=../7_RESULTS/width_3cycl_3Fnyq/PW_2E5Pa_1micron_1MHz_2E5LS/INCS_PW_2E5Pa_1micron_1MHz_2E5LS.out
#SBATCH --error=../7_RESULTS/width_3cycl_3Fnyq/PW_2E5Pa_1micron_1MHz_2E5LS/INCS_PW_2E5Pa_1micron_1MHz_2E5LS.err
 
module use /opt/insy/modulefiles
module load intel
 
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/bin/compilervars.sh intel64
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/mpi/bin64/mpivars.sh
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/mkl/bin/mklvars.sh intel64
 
ulimit -a
ulimit -s unlimited
ulimit -a
ulimit -l unlimited
 
# export I_MPI_PMI_LIBRARY=/home/opt/slurm/slurm-17.11.5/src/api/.libs/libpmi.so
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
#export MKL_THREADING_LAYER=intel
#export MKL_DYNAMIC=FALSE
#export MKL_VERBOSE=1
srun ../7_RESULTS/width_3cycl_3Fnyq/PW_2E5Pa_1micron_1MHz_2E5LS/INCS_Agis_PW_2E5Pa_1micron_1MHz_2E5LS TESTNeumann_Planewave_MultiLinear.in TESTNeumann ../5_INPUT_FILES ../7_RESULTS/width_3cycl_3Fnyq/PW_2E5Pa_1micron_1MHz_2E5LS
