#!/bin/bash  									 															
   											 															
#SBATCH --job-name=250deg_left_wave  	 																		
#SBATCH --partition=general  					 															
#SBATCH --qos=short           				 															
#SBATCH --nodes=1            					 															
#SBATCH --ntasks-per-node=50  				 															
#SBATCH --cpus-per-task=1      				 															
#SBATCH --mem-per-cpu=9G             				 															
#SBATCH --time=04:00:00       				 															
#SBATCH --output=//tudelft.net/staff-groups/tnw/ist/ak/Promovendi/agismatalliota//7_RESULTS/ProtonBubble_TestCases/1E6PS_1_7MHz_Cube_p52/INCS_David_250deg_left_MBs_FullNL_3_5Fnyq_p52.out  					 															
#SBATCH --error=//tudelft.net/staff-groups/tnw/ist/ak/Promovendi/agismatalliota//7_RESULTS/ProtonBubble_TestCases/1E6PS_1_7MHz_Cube_p52/INCS_David_250deg_left_MBs_FullNL_3_5Fnyq_p52.err      				 															
##SBATCH --exclusive           				 															
   											 															
module use /opt/insy/modulefiles  			 															
module load intel  							 															
   											 															
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/bin/compilervars.sh intel64  		
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/mpi/bin64/mpivars.sh  				
source /opt/insy/intel/2017u4/compilers_and_libraries_2017.4.196/linux/mkl/bin/mklvars.sh intel64  		
   																										
ulimit -s unlimited  																						
   																										
# export I_MPI_PMI_LIBRARY=/home/opt/slurm/slurm-17.11.5/src/api/.libs/libpmi.so  						
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so  															
export OMP_NUM_THREADS=1  																				
export MKL_NUM_THREADS=1  																				
#export MKL_THREADING_LAYER=intel  																		
#export MKL_DYNAMIC= FALSE   																				
#export MKL_VERBOSE=1  																					
srun ../3_COMPILED_FILES/INCS_p52 TESTNeumann_PointSourceCloud_MultiBubble_copy.in TESTNeumann ../7_RESULTS/ProtonBubble_TestCases/1E6PS_1_7MHz_Cube_p52/p52 ../7_RESULTS/ProtonBubble_TestCases/1E6PS_1_7MHz_Cube_p52/p52
